name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 20
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run Script
      working-directory: ./builder
      env:
        S_IMAGE_NAME: "papermc"
        S_IMAGE_PLATFORMS: "linux/arm/v7,linux/arm64/v8,linux/amd64"
        S_DOCKER_NAMESPACE: "parzivalspace"
        S_DOCKER_TOKEN: ""
        S_GITHUB_USER: "parzival-space"
        S_GITHUB_TOKEN: ""
      run: |
        npm ci
        node .
