name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: automated-publish-task
  cancel-in-progresss: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 20
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run Script
      working-directory: ./builder
      env:
        VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
        VAR_IMAGE_PLATFORMS: ${{ vars.TARGET_PLATFORMS }}
        VAR_DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}
        VAR_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        VAR_GITHUB_USER: ${{ github.repository_owner }}
        VAR_GITHUB_TOKEN: ${{ github.token }}
      run: |
        npm ci
        node .
